/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface ConfigResponse {
  admin: Addr;
  base_token_uri: string;
  collection_uri?: string | null;
  name: string;
  nft_address?: Addr | null;
  nft_remaining: number;
  payment_address?: Addr | null;
  price: Coin;
  seller_fee_bps: number;
  symbol: string;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface Config {
  admin: Addr;
  base_token_uri: string;
  collection_uri?: string | null;
  name: string;
  payment_address?: Addr | null;
  price: Coin;
  seller_fee_bps: number;
  symbol: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  mint: {
    [k: string]: unknown;
  };
};
export interface InstantiateMsg {
  admin: string;
  base_token_uri: string;
  collection_uri?: string | null;
  name: string;
  nft_limit: number;
  payment_address?: string | null;
  price: Coin;
  seller_fee: number;
  symbol: string;
}
export type QueryMsg = {
  config: {};
};