/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Addr, Expiration, Timestamp, Uint64, Uint128, Scheduled, ConfigResponse, StageResponse, Coin, Config, ExecuteMsg, InstantiateMsg, Stage, QueryMsg } from "./Bs721Launchpad.types";
export interface Bs721LaunchpadReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
}
export class Bs721LaunchpadQueryClient implements Bs721LaunchpadReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
}
export interface Bs721LaunchpadInterface extends Bs721LaunchpadReadOnlyInterface {
  contractAddress: string;
  sender: string;
  mint: ({
    proofs,
    stage
  }: {
    proofs: string[];
    stage: number;
  }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export class Bs721LaunchpadClient extends Bs721LaunchpadQueryClient implements Bs721LaunchpadInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.mint = this.mint.bind(this);
  }

  mint = async ({
    proofs,
    stage
  }: {
    proofs: string[];
    stage: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      mint: {
        proofs,
        stage
      }
    }, fee, memo, funds);
  };
}