/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Bs721Base.types";
import * as _1 from "./Bs721Base.client";
import * as _2 from "./Bs721Base.message-composer";
import * as _3 from "./Bs721Launchpad.types";
import * as _4 from "./Bs721Launchpad.client";
import * as _5 from "./Bs721Launchpad.message-composer";
export namespace contracts {
  export const Bs721Base = { ..._0,
    ..._1,
    ..._2
  };
  export const Bs721Launchpad = { ..._3,
    ..._4,
    ..._5
  };
}